# Generated by Django 5.2.3 on 2026-03-15 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The full destination URL.', max_length=2048)),
                ('short_code', models.CharField(db_index=True, help_text='Unique identifier used in the short URL path.', max_length=50, unique=True)),
                ('is_custom', models.BooleanField(default=False, help_text='True if the user provided a custom alias.')),
                ('title', models.CharField(blank=True, default='', help_text='Optional display name for the link.', max_length=255)),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Total number of redirect hits. Updated atomically.')),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Timestamp of the last successful redirect.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When set, redirects fail with 410 after this time.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive links return 410 Gone without being deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user who owns this link.', on_delete=django.db.models.deletion.CASCADE, related_name='shortened_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Visitor IP address.', null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('referer', models.CharField(blank=True, default='', max_length=2048, verbose_name='HTTP Referer')),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='urls_app.shortenedurl')),
            ],
            options={
                'verbose_name': 'Click Event',
                'verbose_name_plural': 'Click Events',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['short_code'], name='urls_app_sh_short_c_e8a251_idx'),
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['owner', '-created_at'], name='urls_app_sh_owner_i_558b84_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['shortened_url', '-clicked_at'], name='urls_app_cl_shorten_534f43_idx'),
        ),
    ]
